# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Seat.create(label: '1', bus_id: 1)
Seat.create(label: '2', bus_id: 1)
Seat.create(label: '3', bus_id: 1)
Seat.create(label: '4', bus_id: 1)
Seat.create(label: '5', bus_id: 1)
Seat.create(label: '6', bus_id: 1)
Seat.create(label: '7', bus_id: 1)
Seat.create(label: '8', bus_id: 1)
Seat.create(label: '9', bus_id: 1)
Seat.create(label: '10', bus_id: 1)
Seat.create(label: '11', bus_id: 1)
Seat.create(label: '12', bus_id: 1)
Seat.create(label: '13', bus_id: 1)
Seat.create(label: '14', bus_id: 1)
Seat.create(label: '15', bus_id: 1)
Seat.create(label: '16', bus_id: 1)
Seat.create(label: '17', bus_id: 1)
Seat.create(label: '18', bus_id: 1)
Seat.create(label: '19', bus_id: 1)
Seat.create(label: '20', bus_id: 1)
Seat.create(label: '21', bus_id: 1)
Seat.create(label: '22', bus_id: 1)
Seat.create(label: '23', bus_id: 1)
Seat.create(label: '24', bus_id: 1)
Seat.create(label: '25', bus_id: 1)
Seat.create(label: '26', bus_id: 1)
Seat.create(label: '27', bus_id: 1)
Seat.create(label: '28', bus_id: 1)
Seat.create(label: '29', bus_id: 1)
Seat.create(label: '30', bus_id: 1)
Seat.create(label: '31', bus_id: 1)